class Difference:\n",
        def __init__(self, a):\n",
            self.__elements = a\n",
            self.maximumDifference=0\n",
    \t# Add your code here\n",
        def computeDifference(self): \n",
            self.maximumDifference=abs(max(self.__elements)-min(self.__elements))\n",
    \n",
    # End of Difference class\n",
    \n",
    _ = input()\n",
    a = [int(e) for e in input().split(' ')]\n",
    \n",
    d = Difference(a)\n",
    d.computeDifference()\n",
    \n",
    print(d.maximumDifference)"
