from abc import ABCMeta, abstractmethod\n",
    class Book(object, metaclass=ABCMeta):\n",
        def __init__(self,title,author):\n",
            self.title=title\n",
            self.author=author   \n",
        @abstractmethod\n",
        def display(): pass\n",
    \n",
    #Write MyBook class\n",
    class MyBook(Book):\n",
        def __init__(self, title, author, price):\n",
            Book.__init__(self,title, author)\n",
            self.price=price\n",
        \n",
        def display(self):\n",
            print(\"Title: {0}\\nAuthor: {1}\\nPrice: {2}\\n\".format(self.title,\\\n",
            self.author,self.price))\n",
    "\n",
    "\n",
    "\n",
    title=input()\n,
    author=input()\n,
    price=int(input())\n,
    new_novel=MyBook(title,author,price)\n,
    new_novel.display()\n,
    \n",
