    class Person:\n",
    \tdef __init__(self, firstName, lastName, idNumber):\n",
    \t\tself.firstName = firstName\n",
    \t\tself.lastName = lastName\n",
    \t\tself.idNumber = idNumber\n",
    \tdef printPerson(self):\n",
    \t\tprint(\"Name:\", self.lastName + \",\", self.firstName)\n",
    \t\tprint(\"ID:\", self.idNumber)\n",
    \n",
    class Student(Person):\n",
        #   Class Constructor\n",
        \n",
        #   Parameters:\n",
        #   firstName - A string denoting the Person's first name.\n",
        #   lastName - A string denoting the Person's last name.\n",
        #   id - An integer denoting the Person's ID number.\n",
        #   scores - An array of integers denoting the Person's test scores.\n",
        #\n",
        # Write your constructor here\n",
        def __init__(self, firstName, lastName, idNumber, score):\n",
           Person.__init__(self, firstName, lastName, idNumber)\n",
           self.scores=score\n",
    \n",
        def calculate(self):\n",
            average=sum(scores)/len(scores)\n",
            if average<101 and average>89:\n",
                return 'O'\n",
            elif average>79 and average<90:\n",
                return 'E'\n",
            elif average>69 and average<80:\n",
                return 'A'\n",
            elif average>54 and average<70:\n",
                return 'P'\n",
            elif average>39 and average<55:\n",
                return 'D'\n",
            elif average<40 :\n",
                return 'T'\n",
              
        #   Function Name: calculate\n",
        #   Return: A character denoting the grade.\n",
        #\n",
        # Write your function here\n",
    \n",
    line = input().split()\n",
    firstName = line[0]\n",
    lastName = line[1]\n",
    idNum = line[2]\n",
    numScores = int(input()) # not needed for Python\n",
    scores = list( map(int, input().split()) )\n",
    s = Student(firstName, lastName, idNum, scores)\n",
    s.printPerson()\n",
    print(\"Grade:\", s.calculate())\n",
    \n",
